using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using ConfigureServiceExample.Services;

namespace ConfigureServiceExample
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<ILogger, Logger>();
        }

        public void Configure(IApplicationBuilder app, ILogger logger)
        {
			//app.UseRouting();

			app.Use(async (context, next) =>
            {
                logger.Log("Logged line\n");
				string msg = string.Format("{0} {1} {2}",
					"This text was generated by the app.Use middleware. The request path is:",
					context.Request.Path.Value, "\n");

                await context.Response.WriteAsync(msg);
				await next.Invoke();
            });

			app.Run(async (context) =>
			{
				await context.Response.WriteAsync("This text was generated by the app.Run middleware.");
			});

		}
    }
}
